#!/bin/bash
# RPISFT was made by the Raspberry Pi Software organization. This program is used to install packages, uninstall packages etc.
package_list=();
if [[ $1 == "first-installation" ]]; then
  echo "RPISFT> Making configuration...";
  sudo touch /etc/rpisftware.conf;
  sudo echo "packages_dir=/etc/rpisftware.aad" >> /etc/rpisftware.conf
  sudo mkdir -p /etc/rpisftware.aad;
  echo "RPISFT> Made configuration.";
  echo "RPISFT> Adding default packages...";
  sudo mkdir -p /etc/rpisftware.aad/packages/;
  sudo touch /etc/rpisftware.aad/packages/default.pack;
  sudo echo "dtpt=null\nallow-install=true" >> /etc/rpisftware.aad/packages/default.pack;
  echo "RPISFT> Finished installing default packages.";
  echo "RPISFT> Exiting...";
fi;
if [[ $1 == "install" && $2 ]]; then
  echo "Indexing package list...";
  wget -q https://cdn.githubraw.com/Raspberry-Pi-Software/package-list/main/package-list.txt;
  while IFS="" read -r p || [ -n "$p" ]
  do
    # $p is the item of newline
    package_list+=("$p");
  done < package-list.txt
  echo "Updated package list.";
  rm package-list.txt;
  echo "Finding package '$2'...";
  package_exists=false;
  for i in $package_list;
  do
      if [[ $i == $2 ]]; then
        if [[ $package_exists == true ]]; then
          echo "Uh oh, we found duplicate packages!";
          echo "There was an error finding $2 as there is 2 packages of the same name.";
          echo "Submit this as an issue here: https://github.com/Raspberry-Pi-Software/issues/issues";
          exit;
        else
          echo "Package found.";
          package_exists=true;
        fi;
      fi;
  done
  if [[ $package_exists == true ]]; then
    echo "Installing...";
  else
    echo "Package wasn't found. No such package or not in index.";
    exit;
  fi;
  git clone --quiet https://github.com/Raspberry-Pi-Software/$2 &> /dev/null
  if [[ -d $2 ]]; then
    echo "Moving package...";
    sudo mv ./$2 /etc/rpisftware.aad/packages/$2;
    echo "Moved. Checking for install script...";
    if [[ -d /etc/rpisftware.aad/packages/$2/ ]]; then 
        if [[ -e /etc/rpisftware.aad/packages/$2/post-install ]]; then
            sudo bash "/etc/rpisftware.aad/packages/$2/post-install";
        fi;
        echo "Installed $2 successfully."
    else
      echo "Error. Package not installed correctly...";
      exit;
    fi;
  else
    echo "Error installing package. Package doesn't exist."
  fi;
fi;
